replicaCount: 1

image:
  repository: smartcitiesdata/andi
  tag: 0.2.3
  pullPolicy: Always

monitoring:
  targetPort: 80

redis:
  host: redis.external-services

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  securityGroups: ""
  certificateARN: ""
  dnsZone: "localhost"

resources:
  limits:
    memory: 512Mi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 100m
