apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      serviceAccountName: discovery-api
      containers:
      - name: discovery-api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: KAFKA_BROKERS
            value: {{ .Values.kafka.brokers }}
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
{{- if .Values.redis.password }}
          - name: REDIS_PASSWORD
            value: {{ .Values.redis.password }}
{{- end }}
          - name: PRESTO_URL
            value: {{ .Values.presto.url }}
          - name: PRESTO_CATALOG
            value: {{ .Values.presto.catalog }}
          - name: PRESTO_SCHEMA
            value: {{ .Values.presto.schema }}
          - name: HOST
            value: data.{{ .Values.ingress.rootDnsZone }}
          - name: ALLOWED_ORIGINS
            value: {{ .Values.ingress.rootDnsZone }},{{ .Values.ingress.dnsZone }}
          - name: LDAP_HOST
            value: {{ .Values.ldap.host }}
          - name: LDAP_BASE
            value: {{ .Values.ldap.base }}
          - name: LDAP_USER
            value: {{ .Values.ldap.user }}
          - name: LDAP_ACCOUNT_SUBDN
            value: {{ .Values.ldap.account.subdn }}
          - name: PRESIGN_KEY
            valueFrom:
              secretKeyRef:
                name: discovery-api-presign-key
                key: discovery-api-presign-key
          - name: LDAP_PASS
            valueFrom:
              secretKeyRef:
                name: ldap
                key: password
          - name: GUARDIAN_KEY
            valueFrom:
              secretKeyRef:
                name: guardian
                key: secret_key
          - name: HOSTED_FILE_BUCKET
            value: {{ .Values.environment }}-{{ .Values.s3.hostedFileBucket }}
          - name: HOSTED_FILE_REGION
            value: {{ .Values.s3.hostedFileRegion }}
          - name: SECRETS_ENDPOINT
            value: {{ .Values.vault.endpoint }}
          - name: POSTGRES_HOST
            value: {{ .Values.postgres.host }}
          - name: POSTGRES_DBNAME
            value: {{ .Values.postgres.dbname }}
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password }}
          - name: POSTGRES_PORT
            value: {{ quote .Values.postgres.port }}
          - name: AUTH_PROVIDER
            value: {{ quote .Values.auth.provider }}
          - name: AUTH_JWT_ISSUER
            value: {{ printf "https://%s/" .Values.auth.domain | quote}}
          - name: AUTH_JWKS_ENDPOINT
            value: {{ printf "https://%s/.well-known/jwks.json" .Values.auth.domain | quote}}
          - name: AUTH_USER_INFO_ENDPOINT
            value: {{ printf "https://%s/userinfo" .Values.auth.domain | quote}}
          - name: AUTH_DOMAIN
            value: {{ quote .Values.auth.domain }}
          - name: AUTH_CLIENT_ID
            value: {{ quote .Values.auth.client_id }}
          - name: AUTH_REDIRECT_BASE_URL
            value: {{ quote .Values.auth.redirect_base_url }}
